//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_FİnalProject_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestion
    {
        public int id { get; set; }
        public int Subject_ID { get; set; }
        public string Content { get; set; }
        public string Correct { get; set; }
        public string Incorrect1 { get; set; }
        public string Incorrect2 { get; set; }
        public string Incorrect3 { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
